### ISSUE TITLE
Vérifier les contraintes d'utilisation de la licence OpenVSP

### ISSUE THREAD

**Issue by florentLutz** [supaero-aircraft-design/FAST-GA#13]

**Comment by joeljezegou** [comment]
OpenVSP est distribué avec contrat de licence "NASA OPEN SOURCE AGREEMENT VERSION 1.3". Le §3 de cette licence prévoit le cas de la distribution d'OpenVSP par un Recipient, y/c redistribution dans un autre software.
OpenVSP est distribué dans FAST sans que le code source d'OpenVSP soit modifié.
Tant que notre distribution d'OpenVSP se fait respectant les clauses du contrat de licence OpenVSP, nous pouvons distribuer.

Voir ci-dessous 3 actions à mener pour respecter ces clauses :

- "3.A. 1. Whenever a Recipient distributes or redistributes the Subject Software, a copy of this Agreement must be included with each copy of the Subject Software"
**Action 1 ==> (Florent ou Aurélien)** inclure le fichier Licence OpenVSP doit être dans le répertoire OpenVSP que nous distribuons

- "3.A.2. If Recipient distributes or redistributes the Subject Software in any form other than source code, Recipient must also make the source code freely available, and must provide with each copy of the Subject Software information on how to obtain the source code in a reasonable manner on or through a medium customarily used for software exchange."
**Action 2 ==> (Florent ou Aurélien)** nous ne distribuons pas OpenVSP sous une forme différente de l'install classique d'OpenVSP. Dans le répertoire OpenVSP dans FAST, il faut mettre un lien vers le site  OpenVSP pour permettre à un utilisateur d'avoir accès à toutes les sources d'OpenVSP

- "3.B. Each Recipient must ensure that the following copyright notice appears prominently in the Subject Software:
Copyright (c) 2012 United States Government as represented by the Administrator for The National Aeronautics and Space Administration. All Rights Reserved."
==> c'est inclus dans le fichier Licence qui est dans répertoire OPenVSP distribué

- "3.I. A Recipient may create a Larger Work by combining Subject Software with separate software not governed by the terms of this agreement and distribute the Larger Work as a single product. In such case, the Recipient must make sure Subject Software, or portions thereof, included in the Larger Work is subject to this Agreement."
==> c'est notre cas, d'où obligation de respecte les clauses de la licence

- **Action 3 ==> (Joël)** vérifier la clause Export Licence, qui est très générale

**Comment by joeljezegou** [comment]
Action 3 ==> (Joël) vérifier la clause Export Licence, qui est très générale
Nous ne sommes pas en situation de transaction d'exportation en dehors du territoire USA. Pas d'actions complémentaires à mener. Action 3 close
