### ISSUE TITLE
An incorrect variable is being used to compute the aircraft's cl_alpha (VLM method)

### ISSUE THREAD

**Issue by NOTaShinigami** [supaero-aircraft-design/FAST-GA#173]
There's a mismatch in the variable being returned from compute_aero_coeff. The cl_alpha_htp variable, which is used to calculate the cl alpha for the aircraft using vlm, currently corresponds to the cl_aoa_htp rather than the cl_alpha_htp.

**Comment by florentLutz** [comment]
Thanks for the heads-up, it has been corrected. I'm closing the issue
