### ISSUE TITLE
Modifier/compléter les variable description!

### ISSUE THREAD

**Issue by areysset** [supaero-aircraft-design/FAST-GA#78]
Après modification de l'API, les fichiers ont été régénérés (complétés) et des descriptions sont à compléter et des définitions mises au niveau fastga sont à supprimer car apparaissent maintenant dans des sous packages:
Warning: file contains parameter data:aerodynamics:aircraft:mach_interpolation:CL_alpha_vector already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:aircraft:mach_interpolation:mach_vector already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CD already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CL already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CL_max already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CM already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:takeoff:CL already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:flaps:takeoff:CL_max already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CL0_clean already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CL_alpha already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CM0_clean already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:induced_drag_coefficient already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:chord_vector already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL0_clean already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL_alpha already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL_vector already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CM0_clean already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:Y_vector already saved in aerodynamics subpackage !

Warning: file contains parameter data:aerodynamics:horizontal_tail:efficiency already saved in geometry subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:area already saved in handling_qualities subpackage !

Warning: file contains parameter data:geometry:vertical_tail:area already saved in handling_qualities subpackage !

Warning: file contains parameter data:aerodynamics:cruise:neutral_point:free_elevator_factor already saved in handling_qualities subpackage !

Warning: file contains parameter data:aerodynamics:cruise:neutral_point:stick_fixed:x already saved in handling_qualities subpackage !

Warning: file contains parameter data:aerodynamics:cruise:neutral_point:stick_free:x already saved in handling_qualities subpackage !

Warning: file contains parameter data:geometry:wing:area already saved in loops subpackage !

Warning: file contains parameter data:geometry:wing:MAC:at25percent:x already saved in loops subpackage !

Warning: file contains parameter data:mission:sizing:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:initial_climb:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:main_route:climb:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:main_route:cruise:duration already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:main_route:cruise:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:main_route:descent:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:taxi_in:fuel already saved in performances subpackage !

Warning: file contains parameter data:mission:sizing:taxi_out:fuel already saved in performances subpackage !

Warning: file contains parameter data:weight:aircraft:in_flight_variation:fixed_mass_comp:equivalent_moment already saved in cg subpackage !

Warning: file contains parameter data:weight:aircraft:in_flight_variation:fixed_mass_comp:mass already saved in cg subpackage !

Warning: file contains parameter data:weight:aircraft:MTOW already saved in mass_breakdown subpackage !

Warning: file contains parameter data:aerodynamics:aircraft:mach_interpolation:CL_alpha_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:aircraft:mach_interpolation:mach_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CD already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CL already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CL_max already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:landing:CM already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:takeoff:CL already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:flaps:takeoff:CL_max already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:nacelles:cruise:CD0 already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:nacelles:low_speed:CD0 already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:slipstream:wing:cruise:only_prop:CL_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:slipstream:wing:cruise:prop_on:velocity already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:slipstream:wing:cruise:prop_on:Y_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CL0_clean already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CL_alpha already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:CM0_clean already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:cruise:induced_drag_coefficient already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:chord_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL0_clean already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL_alpha already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CL_vector already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:CM0_clean already saved in models subpackage !

Warning: file contains parameter data:aerodynamics:wing:low_speed:Y_vector already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:luggage:mass_max already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:passenger:count_by_row already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:passenger:length already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:passenger:NPAX_max already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:pilot:length already saved in models subpackage !

Warning: file contains parameter data:geometry:flap:chord_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:front_length already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:length already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:luggage_length already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:maximum_height already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:maximum_width already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:PAX_length already saved in models subpackage !

Warning: file contains parameter data:geometry:fuselage:rear_length already saved in models subpackage !

Warning: file contains parameter data:geometry:has_T_tail already saved in models subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:area already saved in models subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:elevator_chord_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:sweep_25 already saved in models subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:taper_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:horizontal_tail:thickness_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:landing_gear:height already saved in models subpackage !

Warning: file contains parameter data:geometry:landing_gear:type already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:count already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:layout already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:nacelle:length already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:nacelle:wet_area already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:nacelle:width already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:nacelle:y already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:propeller:depth already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:propeller:diameter already saved in models subpackage !

Warning: file contains parameter data:geometry:propulsion:y_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:area already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:aspect_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:max_thickness:x_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:sweep_25 already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:taper_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:thickness_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:area already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:aspect_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:kink:span_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:MAC:at25percent:x already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:sweep_25 already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:taper_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:wing:thickness_ratio already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:cs23:sizing_factor_ultimate already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:landing:elevator_angle already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:cruise:altitude already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:elevator_angle already saved in models subpackage !

Warning: file contains parameter data:propulsion:IC_engine:fuel_type already saved in models subpackage !

Warning: file contains parameter data:TLAR:category already saved in models subpackage !

Warning: file contains parameter data:TLAR:level already saved in models subpackage !

Warning: file contains parameter data:TLAR:luggage_mass_design already saved in models subpackage !

Warning: file contains parameter data:TLAR:NPAX_design already saved in models subpackage !

Warning: file contains parameter data:TLAR:range already saved in models subpackage !

Warning: file contains parameter data:TLAR:v_approach already saved in models subpackage !

Warning: file contains parameter data:TLAR:v_cruise already saved in models subpackage !

Warning: file contains parameter data:TLAR:v_limit already saved in models subpackage !

Warning: file contains parameter data:TLAR:v_max_sl already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:CG:aft:x already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:CG:flight_condition:max:MAC_position already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:CG:flight_condition:min:MAC_position already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:CG:fwd:x already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:MTOW already saved in models subpackage !

Warning: file contains parameter data:weight:aircraft:OWE already saved in models subpackage !

Warning: file contains parameter data:weight:airframe:fuselage:k_factor already saved in models subpackage !

Warning: file contains parameter data:weight:airframe:horizontal_tail:k_factor already saved in models subpackage !

Warning: file contains parameter data:weight:airframe:vertical_tail:k_factor already saved in models subpackage !

Warning: file contains parameter data:weight:airframe:wing:k_factor already saved in models subpackage !

Warning: file contains parameter data:weight:propulsion:engine:mass already saved in models subpackage !

Warning: file contains parameter data:weight:propulsion:unusable_fuel:mass already saved in models subpackage !

Warning: file contains parameter settings:weight:aircraft:CG:aft:MAC_position:margin already saved in models subpackage !

Warning: file contains parameter settings:weight:aircraft:CG:fwd:MAC_position:margin already saved in models subpackage !

Warning: file contains parameter settings:weight:aircraft:CG:range already saved in models subpackage !

Warning: file contains parameter settings:weight:aircraft:payload:design_mass_per_passenger already saved in models subpackage !

Warning: file contains parameter settings:weight:aircraft:payload:max_mass_per_passenger already saved in models subpackage !

Warning: file contains parameter settings:weight:airframe:landing_gear:front:weight_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:flap:span_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:flap_type already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:blades_number already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:chord_vect already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:diameter already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:hub_diameter already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:radius_ratio_vect already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:sweep_vect already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:twist_vect already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:rudder:chord_ratio already saved in models subpackage !

Warning: file contains parameter data:geometry:vertical_tail:rudder:max_deflection already saved in models subpackage !

Warning: file contains parameter data:handling_qualities:static_margin:target already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:initial_climb:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:landing:flap_angle already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:climb:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:cruise:duration already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:cruise:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:descent:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:reserve:duration already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:flap_angle already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_in:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_out:fuel already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:aisle_width already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:passenger:width already saved in models subpackage !

Warning: file contains parameter data:geometry:cabin:seats:pilot:width already saved in models subpackage !

Warning: file contains parameter data:geometry:propeller:depth already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:holding:fuel already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:climb:climb_rate:cruise_level already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:climb:climb_rate:sea_level already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:main_route:descent:descent_rate already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:friction_coefficient_no_brake already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:takeoff:thrust_rate already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_in:duration already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_in:speed already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_in:thrust_rate already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_out:duration already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_out:speed already saved in models subpackage !

Warning: file contains parameter data:mission:sizing:taxi_out:thrust_rate already saved in models subpackage !

Warning: file contains parameter data:propulsion:IC_engine:max_power already saved in models subpackage !

Warning: file contains parameter data:propulsion:IC_engine:max_rpm already saved in models subpackage !

Warning: file contains parameter data:propulsion:IC_engine:strokes_nb already saved in models subpackage !

Warning: file contains parameter data:weight:propulsion:tank:mass already saved in models subpackage !

**Comment by florentLutz** [comment]
An issue has been found in which the variable_descriptions were not read. A workaround has been found and an issue was created on fast-oad. This will stay open for now.
